### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by rubyFeedback** [mattiasgustavsson/dos-like#13]
Just found the project via reddit mention so my comment here is a bit "random".

Do you think it would be possible to just add a few screenshots to the main README? Does not have
to be many, say, 3 or so, as an overview toshow what is working - and homage to nostalgia!

(And perhaps if you have time and motivation to mention differences to dosbox dosbox-X and any
other project, e. g. to understand people the "identity" of "dos-like", in relation to these other
projects.)

**Comment by mattiasgustavsson** [comment]
Thanks for the suggestions, I have updated the readme
