### ISSUE TITLE
No audio output for Linux builds

### ISSUE THREAD

**Issue by LJNIC** [mattiasgustavsson/dos-like#29]
None of the examples built for Linux are producing sound, however the Windows ones do work with Wine.

Linux: Pop OS 21.04

**Comment by mattiasgustavsson** [comment]
I don’t run Linux myself, so I am not able to look into it. I know that there are others who run Linux that do get sound though. You might want to add some more information about what Linux version you use etc, so that maybe someone else may give some advice

**Comment by LJNIC** [comment]
I was mistaken! It's actually the `readchars` function in the `sound.c` example that isn't returning anything on Linux.

**Comment by mattiasgustavsson** [comment]
Yeah, looking at the code it seems like I am not handling the SDL_TEXTINPUT event in the SDL implementation in app.h. Shouldn’t be too hard to add, once I get some time to look into it.

**Comment by mattiasgustavsson** [comment]
Should be fixed with PR #30
