### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by johanberntsson** [mattiasgustavsson/dos-like#3]
Without a license file or licensing information in README.md it is hard to know if how this can be used to create own games/demos/content. Some of the source files contains licensing info but it is conflicting and on a file-by-file basis. Would be good to clarify.

**Comment by mattiasgustavsson** [comment]
Yes, it is using libraries which have different licenses. Each file should contain licensing information, unless I have missed something. There is no single license for the whole thing though.
