### ISSUE TITLE
Free Pascal bindings please? (both FPIDE and Lazarus bindings for both windows and linux)

### ISSUE THREAD

**Issue by TheRealHamtaro126** [mattiasgustavsson/dos-like#38]
Can I have both FPIDE and Lazarus bindings for at least 64 bit Windows 10 as well as a target for 64-bit Linux as well for those willing to go with Free Pascal for linux? This should be a treat for those still having problems with the plain Free Pascal SDL2 package on Github.

I very much appreciate it.

**Comment by mattiasgustavsson** [comment]
Bindings for other languages is not something I do, but maybe someone out there will decide to do it. If so, I’ll be happy to link to it from the readme, like I do for the rust and python bindings
