### ISSUE TITLE
Display options

### ISSUE THREAD

**Issue by bsturk** [mattiasgustavsson/dos-like#42]
Is there a way to not have any of the effects etc and end up with a 320x200 (or 80x25 char) sharp screen?  I figured out how to disable the CRT frame w/ a preproc define, but I can't find how the crtemu can be disabled.

**Comment by mattiasgustavsson** [comment]
There is no built-in way to disable the CRT shader, and I don't think I would want that option, as it will make the aspect ratio wrong compared to dos. 
However, you can modify the code to do it for your own builds if you like. Get rid of the calls to `crtemu_pc_present` here https://github.com/mattiasgustavsson/dos-like/blob/bcdec4259db66c764dbf02f16e2bc40198924091/source/dos.h#L3514
and change the `app_present( app, NULL, 1, 1, 0xffffff, 0xff1a1a1a );` a few lines down to `app_present( app, screen_xbgr, width, height, 0xffffff, 0xff1a1a1a );`
