### ISSUE TITLE
Cannot find CreateShader

### ISSUE THREAD

**Issue by VictorHM** [mattiasgustavsson/dos-like#44]
After compiling it with `build_all.bat`, I run any of the executables and this is the message I get every time:
![error shader](https://github.com/mattiasgustavsson/dos-like/assets/2629126/a10fb49c-a1cb-4b92-99bf-e585bd0902d4)
The thing is that after that, it seems to work. At least most of them.

I will try to investigate on my own when I have time, but I think it is worth opening the issue in case it is a known issue and has a simple solution.

**Comment by mattiasgustavsson** [comment]
Hmm, that sounds like it could be a graphics card driver issue maybe. I’ll take a look though

**Comment by VictorHM** [comment]
You were completely correct! I had an update of the driver waiting for update. Once it was updated, recompiled (just in case) and it works without any problem. We can mark this as done. Thank you for the quick response y for this repository!
