### ISSUE TITLE
Not clear what it does

### ISSUE THREAD

**Issue by realmazharhussain** [mattiasgustavsson/dos-like#6]
I couldn't understand what your program does. Could you add a detailed description of your program where you write what exactly does your program do?

**Comment by excalith** [comment]
Readme says that it is an engine for making things, such as games and visual arts etc. Think about Unity 3D, Unreal Engine alike - but without that much tools. You write programs yourself (check stranded example) and launch it with dos-like.

**Comment by ralfbiedert** [comment]
Can't speak for OP but I think the [project page you link](https://mattiasgustavsson.itch.io/dos-like) does a much better job visualizing what dos-like does. I think if you added a section "What does dos-like do?" (scnr) to the README and added some screenshots from here

![image](https://user-images.githubusercontent.com/301288/136656297-6b8d97a1-040e-467b-8154-e84e53fb5b1f.png)

along with this section 

![image](https://user-images.githubusercontent.com/301288/136656305-ab06c83c-12a2-492e-8128-fc389f98f95a.png)

then people landing on Github first got a better chance to grok the project. Nice demos btw, the audio UI gave me warm fuzzy flashbacks :)

**Comment by excalith** [comment]
Sounds like a nice PR opportunity! Anyone up for it? Can do it in the evening
