### ISSUE TITLE
Crashes on Linux/Xorg

### ISSUE THREAD

**Issue by thp** [mattiasgustavsson/dos-like#7]
This crashes on Linux for me (using a Xorg session, not Wayland), the issue seems unrelated to #2:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x6005c9
  Serial number of failed request:  270
  Current serial number in output stream:  270
```

Commenting out `SDL_HideWindow( app->window );` in `dos.h` fixed the issue for me, but not sure if it's a reasonable fix.

**Comment by mattiasgustavsson** [comment]
That sounds great, yes, will do that

**Comment by mattiasgustavsson** [comment]
Hopefully this should be fixed now, so closing the issue for now
